//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_time: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::menu_data::Entity")]
    MenuData,
}

impl Related<super::menu_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
