//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::dish::Entity as Dish;
pub use super::dish_product::Entity as DishProduct;
pub use super::dishes_scheme::Entity as DishesScheme;
pub use super::menu::Entity as Menu;
pub use super::menu_data::Entity as MenuData;
pub use super::product::Entity as Product;
