//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3
#[allow(unused_imports)]
pub use super::dish::Entity as Dish;
#[allow(unused_imports)]
pub use super::dish_product::Entity as DishProduct;
#[allow(unused_imports)]
pub use super::dishes_scheme::Entity as DishesScheme;
#[allow(unused_imports)]
pub use super::menu::Entity as Menu;
#[allow(unused_imports)]
pub use super::menu_data::Entity as MenuData;
#[allow(unused_imports)]
pub use super::product::Entity as Product;
