//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub measure: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dish_product::Entity")]
    DishProduct,
}

impl Related<super::dish_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DishProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
