[workspace]
members = [
    "dhe_menu",
    "dhe_translate",
    "dhe_sdk",
    "dhe_sdk_macros",
]

[workspace.dependencies]
strum = { version = "0.24", features = ["derive"] }
thiserror = "1.0.38"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.37"