[package]
name = "dhe_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dhe_sdk = { path = "../dhe_sdk" }
dhe_sdk_macros = { path = "../dhe_sdk_macros" }
iced = "0.12.1"
notify-rust = "4.8.0"
tracing = { workspace = true }
