[package]
name = "dhe_translate"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.2.0"
dhe_sdk = { path = "../dhe_sdk" }
dhe_sdk_macros = { path = "../dhe_sdk_macros" }
notify-rust = "4.8.0"
tracing = { workspace = true }
tokio = { workspace = true }
